//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Enfermedad_Cliente = new HashSet<Enfermedad_Cliente>();
            this.Registro_citas = new HashSet<Registro_citas>();
            this.Tratamiento_Cliente = new HashSet<Tratamiento_Cliente>();
        }
    
        public int id_cliente { get; set; }
        public int cedula { get; set; }
        public string genero { get; set; }
        public string fecha_nacimiento { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string correo { get; set; }
        public int id_provincia { get; set; }
        public int id_canton { get; set; }
        public int id_distrito { get; set; }
        public string direccion { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Enfermedad_Cliente> Enfermedad_Cliente { get; set; }
        public virtual ICollection<Registro_citas> Registro_citas { get; set; }
        public virtual ICollection<Tratamiento_Cliente> Tratamiento_Cliente { get; set; }
    }
}
