//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctores
    {
        public Doctores()
        {
            this.Registro_citas = new HashSet<Registro_citas>();
        }
    
        public int id_Doctor { get; set; }
        public int cedula { get; set; }
        public string genero { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public string telefono_principal { get; set; }
        public string telefono_secundario { get; set; }
        public string correo_electronico { get; set; }
        public int carne_codigo_respectivo { get; set; }
        public int id_provincia { get; set; }
        public int id_canton { get; set; }
        public int id_distrito { get; set; }
        public string direccion { get; set; }
        public int especialidad_medica { get; set; }
        public int hora_almuerzo { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Especialidad_Medica Especialidad_Medica1 { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Registro_citas> Registro_citas { get; set; }
    }
}
