//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad_Medica
    {
        public Especialidad_Medica()
        {
            this.Doctores = new HashSet<Doctores>();
            this.Registro_citas = new HashSet<Registro_citas>();
        }
    
        public int id_especialidad { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Doctores> Doctores { get; set; }
        public virtual ICollection<Registro_citas> Registro_citas { get; set; }
    }
}
