//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_citas
    {
        public int id_único { get; set; }
        public int id_doctor { get; set; }
        public int id_cliente { get; set; }
        public System.DateTime fecha_cita { get; set; }
        public int hora_cita { get; set; }
        public int especialidad { get; set; }
        public string observaciones { get; set; }
        public string estado_cita { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Doctores Doctores { get; set; }
        public virtual Especialidad_Medica Especialidad_Medica { get; set; }
    }
}
