//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento_Quirurgico
    {
        public Tratamiento_Quirurgico()
        {
            this.Tratamiento_Cliente = new HashSet<Tratamiento_Cliente>();
        }
    
        public int id_tratamiento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Tratamiento_Cliente> Tratamiento_Cliente { get; set; }
    }
}
