//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Sistema
    {
        public string Id_Usuario { get; set; }
        public string Nombre_Completo { get; set; }
        public string Contrasena { get; set; }
        public string Tipo_Usuario { get; set; }
    }
}
